[common]  
env = "development" # development|production
static = "static" # Bundles, images, stubs, etc. 
js = "bundle.js" # Auto-prefixed with static 
style = "bundle.css" # Auto-prefixed with static 
api = "/api/" # prefix for api endpoints 
hot = true # enables live reload. env must be development and hmr must be set
hmr = "127.0.0.1:8889" # when hot flag is true the bundle is served via jsonp from webpack server 

[server]
template = "template.html.tpl"
address = "0.0.0.0:8888"
serve = "127.0.0.1:8888"

[client]
entry = "index.js"
